# Generated by Django 6.1 on 2026-08-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_tag_alter_listing_buyer_alter_listing_seller_and_more'),
    ]

    operations = [
    migrations.RenameField(
        model_name='producttag',
        old_name='add_at',
        new_name='added_at',
    ),
    migrations.RemoveField(
        model_name='product',
        name='tags',
    ),
    migrations.AddField(
        model_name='product',
        name='tags',
        field=models.ManyToManyField(blank=True, related_name='products', through='shop.ProductTag', to='shop.tag'),
    ),
]