# Generated by Django 6.1 on 2026-08-24 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_add_at_producttag_added_at_alter_product_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductTag',
            new_name='Product_Tag',
        ),
    ]
