# Generated by Django 6.1 on 2026-08-26 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_sku'),
    ]

    operations = [
    ]
