# Generated by Django 6.1 on 2026-08-26 11:18

from django.db import migrations


def populate_sku(apps, schema_editor):
    Product = apps.get_model("shop", "Product")

    for product in Product.objects.all():
        product.sku = f"SKU-{product.id:03d}"
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20260826_1114'),
    ]

    operations = [
        migrations.RunPython(populate_sku),
    ]